### ISSUE TITLE
Change title

### ISSUE THREAD

**Issue by RonanC** [jnordberg/sublime-colorpick#13]
When looking for a colour picker add on for sublime 3 I never even looked at yours because the title is: "Color picker plugin for Sublime Text 2 (Mac OS X)".

The only reason I installed it was because wesleys one was causing sublime to crash on me, I investigated, and yours does work with Sublime 3.

If you change the title you'll get a lot more downloads :)

**Comment by jnordberg** [comment]
Done 🍻
