### ISSUE TITLE
Restrict to "osx" platform on package_control_channel

### ISSUE THREAD

**Issue by rwols** [jnordberg/sublime-colorpick#15]
This package works only on macOS, but there is no precise platform restriction for that in the package_control_channel repository. This causes Windows and Linux users to pointlessly download this package hoping they are getting a color picker for their platform.

**Comment by jnordberg** [comment]
Feel free to create a PR on the package control repo.

**Comment by rwols** [comment]
Why not do it yourself?

**Comment by rwols** [comment]
I don't understand why you closed this. It comes across as though you don't care about this package at all. I'll make the necessary PR sometime in the future.
